# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RtoAnovaCpp <- function(rparam, Y, X, isXvarIn, bIDsexp) {
    .Call('mvabund_RtoAnovaCpp', PACKAGE = 'mvabund', rparam, Y, X, isXvarIn, bIDsexp)
}

RtoGlmAnova <- function(sparam, rparam, Y, X, O, isXvarIn, bIDsexp, lambda) {
    .Call('mvabund_RtoGlmAnova', PACKAGE = 'mvabund', sparam, rparam, Y, X, O, isXvarIn, bIDsexp, lambda)
}

RtoGlm <- function(rparam, Y, X, O) {
    .Call('mvabund_RtoGlm', PACKAGE = 'mvabund', rparam, Y, X, O)
}

RtoGlmSmry <- function(sparam, rparam, Y, X, O, bIDsexp, lambda) {
    .Call('mvabund_RtoGlmSmry', PACKAGE = 'mvabund', sparam, rparam, Y, X, O, bIDsexp, lambda)
}

RtoSmryCpp <- function(rparam, Y, X, bIDsexp) {
    .Call('mvabund_RtoSmryCpp', PACKAGE = 'mvabund', rparam, Y, X, bIDsexp)
}

