# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RtoAnovaCpp <- function(rparam, Y, X, isXvarIn, bID) {
    .Call('_mvabund_RtoAnovaCpp', PACKAGE = 'mvabund', rparam, Y, X, isXvarIn, bID)
}

RtoGlmAnova <- function(sparam, rparam, Y, X, O, isXvarIn, bID, lambda, thread_num) {
    .Call('_mvabund_RtoGlmAnova', PACKAGE = 'mvabund', sparam, rparam, Y, X, O, isXvarIn, bID, lambda, thread_num)
}

RtoGlm <- function(rparam, Y, X, O) {
    .Call('_mvabund_RtoGlm', PACKAGE = 'mvabund', rparam, Y, X, O)
}

RtoGlmSmry <- function(sparam, rparam, Y, X, O, bID, lambda) {
    .Call('_mvabund_RtoGlmSmry', PACKAGE = 'mvabund', sparam, rparam, Y, X, O, bID, lambda)
}

RtoSmryCpp <- function(rparam, Y, X, bID) {
    .Call('_mvabund_RtoSmryCpp', PACKAGE = 'mvabund', rparam, Y, X, bID)
}

